const current_narrative = [
    {
        "title": "The Long Nap is Over",
        "date": "March 5, 2026",
        "body": "**Maybe you're reading this** because you're following a link from Facebook or Instagram. If so, congratulations! You made it out.\n\nIt's just you and me now, my friend. \n\n---\n\nI've had this site for 26 years.  When I started outsidetheworld.com back in 2000, there were no Clouds or AIs, no iPhones, no music streaming services. I mean, most of us got our MP3s from Napster over AOL.\n\n**I\u2019ll be the first** to admit that since about 2013, this place has been gathering some serious digital dust. I didn't mean to leave it sitting there like a \"Coming Soon\" sign in an abandoned mall, but life happens, and social media feeds are a hell of a drug. Plus, I got amazingly lazy and handed off this URL to Blogger (of all the damn things).\n\nOver the past three weeks, I\u2019ve been giving the code a thorough cleaning, tidying up the archives, and updating the whole experience. Why? Because the internet can be overwhelming, noisy, and just tiring. I\u2019ve been longing for a space where I can share a daily photo or a longer thought without being trapped by the algorithm (which I am thoroughly afflicted by).\n\n**Here's what I promise:**\n\n* **Long-Form Blogs**: Thoughts that require more than 280 characters and a sense of humanity.\n\n* **Daily Pictures**: A return to the visual rhythm that started it all.\n\n* **The Archives**: 26 years of content. It\u2019s all here. Some of it is poignant; a lot of it is deeply embarrassing evidence of who I was in the late 90s and early 2000s. Browse at your own risk.\n\nSo, poke around. Stay as long as you like. There\u2019s no scroll here\u2014just a finite amount of RyanDavid-made stuff.",
        "file": "2026-03-05-the-long-nap-is-over.md"
    },
    {
        "title": "So much...March",
        "date": "March 4, 2026",
        "body": "**Already the 4th of March**, which means it's already the 3rd month of this, the year of our Lord 2026...\n\nI may have learned most of what I needed to know in kindergarten, but no one prepared me for midlife.  I never expected the burning demand on all sectors of my life to be turned up to such an intensity. I close my eyes and can catch glimpses of parallel universes flitting by, their courses set in motion by a million different daily decisions.  At the end of the day, my gratitude is firm in the most important reality; that where I am right now is where I am supposed to be.  \n\nThose other RyanDavids? They don't experience the joy I receive when I get to take a late-night run to Walmart with my teenage daughter as she desperately searches for a new squishy toy, or the simple pleasure I receive when my pup seats herself next to my thigh and takes a deep breath of relaxation.  No one else gets to have their cup filled by a blue-eyed wife whose tenderness exists in the in-between spaces. And as long as I have Gracie Abrams, David Gray, Sting, Taylor Swift, Colin Hay, et al., all others will stir their jealousy with a oar, not a spoon.\n\nI keep meaning to post this picture I took a few weeks ago at my niece's house in Gold Canyon.  She lives in one of the quietest neighborhoods - actually...scratch that thought.  The fact that I live 100 yards from the railroad tracks gives me zero authority to judge the peacableness and quietude of any location.  Suffice it to say, it's far outside the city limits.  Which also gave me the most remarkable view of the night sky:\n\n![Orion, shaky cam](Images/Blog/night_sky.jpeg)\n\nI tried my best to hold my iPhone steady for the full 10 seconds it took to capture the light.  Aaaaand there may have been some significant post-processing and editing that brought out a few more details.  But still!  What I saw with my naked eye is there in the shot.  I miss the stars.  I pine for the quiet. \n\nRight now, I am writing these posts and sending them straight into the ether.  I derive a modicum of motivation by guarding close the thought that someday soon, I will be launching this site and these may be read.  For now, it's enough to just keep etching my thoughts on the surface of this lake, however ephemeral it feels.",
        "file": "2026-03-04-so-much---march.md"
    },
    {
        "title": "Sunset Sublimity x2",
        "date": "February 28, 2026",
        "body": "**The last two days** have been a right treat for sunsets here in AZ.  Tonight's in particular was especially tasty; one of those viciously red blasts that eminate on the horizon and paint the entire celestial dome with a thousand different shades of orange, pink, purple, and blue. Take a look:\n\n![Saturday Skies](Images/Blog/az_skies.jpeg)\n\nI was especially stoked for this display tonight, as my MIL was in town from Utah and can't get enough of the Sonoran skyscapes.  She landed just in time to catch the tail end of it. Here's to hoping we get another round of God tossing the bucket of paint on us tomorrow.\n\n**While I was on my** long ride this morning, I had a dozen ideas for things to write here for the weekend's entry.  As the day draws to a successfuly close, all those thoughts have flitted away as easily as they came.  I had hoped that as I sat here to type, the gears would turn and shake the cobwebs of excess contemplation, but alas; tis not to be.\n\nMy greatest wish for now is that I can keep up some sort of momentum, and gain back a few of you who used to frequent this site in the decades past.  [Drop me a line](mailto:ryandavid@outsidetheworld.com?subject=OTW) if you do stop by, as I have no other way to gauge visitorship or views at the moment. \n\nThe skeletal framework for OTW is complete.  You can practically hear the sigh of relief as you read this, no?",
        "file": "2026-02-28-sunset-sublimity-x2.md"
    },
    {
        "title": "A Brand New OTW, baby",
        "date": "February 25, 2026",
        "body": "Where have I heard that before?  Surely, at least five times on this site during the past 26 years.    \n  \n**26 years, btw.**   That's how long I've had this domain registered and operating in one form or another.  I finally felt the drive to really sit down and get all of the accumulated digital cruft organized and back online.  So, what you see is the first stage of the process.  I still haven't quite decided whether I will keep the site divided into Personal/Professional ongoing.  But at this point in time, the \"Personal\" site is mostly online and functional.  \n  \nWith the personal side, you'll find a trove of old data on the right side of the screen, separated into \"cards\". The ones most interesting for visitors will likely be [The Archive] and [The Flotsam], for that is where most of the past has been resurrected and then buried again.    \n  \nYou'll also see a bit of boutique linkage in the form of a limited edition run of OTW t-shirts.  These are pretty fabulous unisex shirts that all your friends will pine over, surely.  Why not grab one?  \n  \nThere is certainly more work to be done over the comings weeks, so stay tuned.  At the very least, the OTW blog will be updated regularly again, so there's that.  \n  \nThanks for visiting!",
        "file": "2026-02-25-a-brand-new-otw--baby.md"
    },
    {
        "title": "Maybe, a poem?",
        "date": "February 20, 2026",
        "body": "---\n\nFor as far as you wish    \nFor as long as you stretch    \nIn the moment you lumber    \nIn haste, toward the mountain    \n    \nThe general truth    \nThe uncourteous example    \nNever minding the canopy    \nStretching, aching with heaviness  \n  \nReminder, your cohort  \nBelieves in the coddling fervor  \nThe mind-numbing ache  \nThe key-turn freeing  \n  \nWhat's the angle, then?  \nTo a friend, just perspiration  \nTo our valley below, it's normality  \nDo you remember the promise?  \n  \nSo take wing to the summit  \nThree paths, picked not yet  \nWe may celebrate not the gift  \nAnd yet, burn pleasant all the same",
        "file": "2026-02-20-maybe--a-poem-.md"
    },
    {
        "title": "It's a straight VIBE",
        "date": "February 19, 2026",
        "body": "---\n\nHallelujah, folks. We are back online and fully ready to rock this site back into existence.  \n  \nFor the longest time, I fell back on 3rd party tools and services to help post thoughts to the ether. This was my mechanism for years after I fell into silence while my life took the crazy train without me (with me?) as a passenger. But I digress.  \n  \nBack in 2000, my original site was near pure HTML, with each page created lovingly within Microsoft FrontPage (remember that?) I only once or twice \"borrowed\" code from sting.com, snowbird.com, etc...  \n  \nSince we're partying like it's 1999, OTW is back to pure code, but instead of learning from scratch, I am using Gemini to \"vibe\" with me as I tell it what I want and where I want it. I even created a native posting tool so that I can leave Blogger behind.  \n  \nSo stay tuned,  more magic is guaranteed to manifest itself as the days go on...",
        "file": "2026-02-19-it-s-a-straight-vibe.md"
    }
];