name = "otw-fragments-publish"
main = "src/index.js"
compatibility_date = "2026-03-19"
workers_dev = true

[vars]
GITHUB_OWNER = "ryandavid-oss"
GITHUB_REPO = "outsidetheworld"
GITHUB_BRANCH = "main"
IOTD_PUBLIC_BASE_URL = "https://pub-fd35040d2a3b40af985b8aa67b98eaa8.r2.dev"
NARRATIVE_PUBLIC_BASE_URL = "https://pub-fd35040d2a3b40af985b8aa67b98eaa8.r2.dev"

[[r2_buckets]]
binding = "IOTD_BUCKET"
bucket_name = "otw-iotd"
