name = "otw-fragments-publish"
main = "src/index.js"
compatibility_date = "2026-03-19"
workers_dev = true

[vars]
GITHUB_OWNER = "ryandavid-oss"
GITHUB_REPO = "outsidetheworld"
GITHUB_BRANCH = "main"
