<?php
$pollvars['base_url'] = "/~poll/pollphp/textfile";
$pollvars['base_gif'] = "/~poll/pollphp/textfile/image";
$pollvars['lang'] = "english.php";
$pollvars['title'] = "Advanced Poll";
$pollvars['vote_button'] = "Vote";
$pollvars['result_text'] = "View Results";
$pollvars['total_text'] = "Total Votes";
$pollvars['voted'] = "You have already voted!";
$pollvars['send_com'] = "Send comment";
$pollvars['table_width'] = "170";
$pollvars['img_height'] = "10";
$pollvars['img_length'] = "45";
$pollvars['bgcolor_tab'] = "#FFFFFF";
$pollvars['bgcolor_fr'] = "#666699";
$pollvars['font_color'] = "#000000";
$pollvars['font_face'] = "Verdana, Arial, Helvetica, sans-serif";
$pollvars['result_order'] = "desc";
$pollvars['check_ip'] = "0";
$pollvars['lock_timeout'] = "2";
$pollvars['type'] = "percent";
$pollvars['time_offset'] = "0";
$pollvars['polls_pp'] = "12";
$pollvars['entry_pp'] = "5";
$pollvars['def_options'] = "10";
$pollvars['poll_username'] = "admin";
$pollvars['poll_password'] = "b0f6dfb42fa80caee6825bfecd30f094";
$pollvars['poll_version'] = "2.03";
?>